# Generated by Django 5.2.5 on 2025-08-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='meet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
