# Generated by Django 5.2.5 on 2025-08-29 12:26

from django.db import migrations, models
from django_jsonfield_backport.models import JSONField  # ✅ use this

class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_sessionbooking_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='attendees',
            field=JSONField(blank=True, default=list, null=True),  # ✅ use JSONField from backport
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='calendar_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='meet_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
