# Generated by Django 5.2.5 on 2025-08-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_sessionbooking_attendees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbooking',
            name='time',
        ),
    ]
