# Generated by Django 5.2.5 on 2025-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_sessionbooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
