# Generated by Django 5.2.5 on 2025-08-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_sessionbooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionbooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='event_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
    ]
