# Generated by Django 5.2.5 on 2025-08-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_sessionbooking_options_sessionbooking_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbooking',
            name='time',
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='organizer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
