# Generated by Django 4.1.13 on 2025-08-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_chathistory_userprofile_email_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='default123', max_length=128),
            preserve_default=False,
        ),
    ]
