# Generated by Django 4.1.13 on 2025-09-04 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_mentor_sessionbooking_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='bio',
        ),
        migrations.AddField(
            model_name='mentor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='expertise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
