# Generated by Django 4.1.13 on 2025-09-30 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0013_remove_mentor_bio_mentor_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancedSessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=15)),
                ('event_id', models.CharField(blank=True, max_length=200, null=True)),
                ('calendar_link', models.URLField(blank=True, max_length=500, null=True)),
                ('meet_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attendees', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_sessions', to='chatbot.mentor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enhanced_session_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True, help_text='Admin can check/uncheck availability')),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='chatbot.enhancedsessionbooking')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='chatbot.mentor')),
            ],
            options={
                'db_table': 'time_slots',
                'ordering': ['date', 'start_time'],
                'unique_together': {('mentor', 'date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='MentorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(help_text='Start time of availability (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time of availability (e.g., 17:00)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='chatbot.mentor')),
            ],
            options={
                'db_table': 'mentor_schedules',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('mentor', 'weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='chatbot.mentor')),
            ],
            options={
                'db_table': 'blocked_dates',
                'ordering': ['date'],
                'unique_together': {('mentor', 'date')},
            },
        ),
    ]
