# Generated by Django 4.1.13 on 2025-09-30 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_enhancedsessionbooking_timeslot_mentorschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning_9_930', models.BooleanField(default=False, verbose_name='9:00 AM - 9:30 AM')),
                ('morning_930_10', models.BooleanField(default=False, verbose_name='9:30 AM - 10:00 AM')),
                ('morning_10_1030', models.BooleanField(default=False, verbose_name='10:00 AM - 10:30 AM')),
                ('morning_1030_11', models.BooleanField(default=False, verbose_name='10:30 AM - 11:00 AM')),
                ('morning_11_1130', models.BooleanField(default=False, verbose_name='11:00 AM - 11:30 AM')),
                ('lunch_1130_12', models.BooleanField(default=False, verbose_name='11:30 AM - 12:00 PM')),
                ('lunch_12_1230', models.BooleanField(default=False, verbose_name='12:00 PM - 12:30 PM')),
                ('lunch_1230_1', models.BooleanField(default=False, verbose_name='12:30 PM - 1:00 PM')),
                ('afternoon_1_130', models.BooleanField(default=False, verbose_name='1:00 PM - 1:30 PM')),
                ('afternoon_130_2', models.BooleanField(default=False, verbose_name='1:30 PM - 2:00 PM')),
                ('afternoon_2_230', models.BooleanField(default=False, verbose_name='2:00 PM - 2:30 PM')),
                ('afternoon_230_3', models.BooleanField(default=False, verbose_name='2:30 PM - 3:00 PM')),
                ('afternoon_3_330', models.BooleanField(default=False, verbose_name='3:00 PM - 3:30 PM')),
                ('afternoon_330_4', models.BooleanField(default=False, verbose_name='3:30 PM - 4:00 PM')),
                ('afternoon_4_430', models.BooleanField(default=False, verbose_name='4:00 PM - 4:30 PM')),
                ('afternoon_430_5', models.BooleanField(default=False, verbose_name='4:30 PM - 5:00 PM')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='chatbot.mentor')),
            ],
            options={
                'db_table': 'mentor_availabilities',
                'ordering': ['date'],
                'unique_together': {('mentor', 'date')},
            },
        ),
    ]
