# Generated by Django 4.1.13 on 2025-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_mentoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='display_name',
            field=models.CharField(blank=True, help_text="Custom display name (e.g., 'Vardaan')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_head_mentor',
            field=models.BooleanField(default=False, help_text='Check if this mentor is the head mentor for first-time users'),
        ),
    ]
